#Версия beta-2
#Улучшена механика игры
#Добавленно больше действий
# *прописанна только роль рыцаря

import random
import time

print("Добро пожаловать в королевство")
time.sleep(3)
print("Выберите роль:")
time.sleep(1)
print("1.Рыцарь\n2.Король")
role=input()
if role=="1":
    time.sleep(1)
    print("Теперь вы рыцарь великого королевства")
    time.sleep(3)
    print("Вы много работали в казармах и попали в главные силы королевства")
    time.sleep(3)
    print("Позже вы стали стали командиром одного из полков")
    time.sleep(3)
    print("На ваше королевство напали орки")
    time.sleep(3)
    print("Король приказывает дать достойный отпор противнику")
    time.sleep(3)
    print("Это ваше первое сражение")
    time.sleep(3)
    print("Выберите действие вашего полка в бою")
    time.sleep(1)
    print("1.Агресивные действия\n2.Действия с тактикой главнокомандующего войсками")
    battle=input()
    if battle=="1":
        a=random.randint(0,1)
        if a==0:
            time.sleep(1)
            print("Вы атаковали войска орков")
            time.sleep(3)
            print("Увы они оказались сильнее")
            time.sleep(3)
            print("Вы невовремя проявили свою агрессию")
            time.sleep(3)
            print("Ваше войска разбито, а вы погибли")
            time.sleep(3)
            print("Это нанесло урон по всей армии")
            time.sleep(3)
            print("Game Over!")
        elif a==1:
            print("Вы атаковали войска орков")
            time.sleep(1)
            print("Ваша агрессия оказалась очень кстати")
            time.sleep(3)
            print("Вам попалось войско неопытных орков ")
            time.sleep(3)
            print("Вы с легкастью одалели их")
            time.sleep(3)
            print("Бой выигран")
            time.sleep(3)
            print("Поздравляю вас!")
            time.sleep(3)
            print("Вы успешно прошли боевое крещение")

    elif battle=="2":
        time.sleep(1)
        print("Вы атаковали войска орков")
        time.sleep(3)
        print("Вы отлично управляете полком")
        time.sleep(3)
        print("Тактика оказалась действующей")
        time.sleep(3)
        print("Ваше королевство победило орков")
        time.sleep(3)
        print("Орки отступили")
        time.sleep(3)
        print("Поздравляю вас!")
        time.sleep(3)
        print("Вы успешно прошли боевое крещение")           
else: print("error") 
